run:
  deadline: 3m

issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - goimports
    - gosimple
    - ineffassign
    - misspell
    - staticcheck
    - structcheck
    - unconvert
    - unused
    - varcheck
    - vet

linters-settings:
  funlen:
    lines: 500
    statements: 80
